name       : rage
version    : 0.4.0
release    : 1
source     :
    - https://download.enlightenment.org/rel/apps/rage/rage-0.4.0.tar.xz : 7ce58419aa5197aa6c33f2e3f9eb9d78ff379cae863d5fa114fd1428d5a1ca0f
homepage   : https://www.enlightenment.org/about-rage
license    : BSD-2-Clause
component  : multimedia.video
summary    : Simple video and audio player written using the Enlightenment Foundation Libraries (EFL)
description: |
    Rage is a simple video and audio player intended to be slick yet simplistic. If you want a simple video player like MPlayer, but with a few more visual niceties, then Rage may be for you. Almost all of the nuts and bolts it relies on for video playback and UI are provided by EFL itself or by something EFL wraps, like GStreamer, Xine, VLC and so on. Since it uses EFL, Rage will work in X11, Wayland, even the raw framebuffer with the Framebuffer console (fbcon) or the Direct Rendering Manager (DMS) subsystem.
builddeps  :
    - pkgconfig(efl)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
